### PR TITLE
refactor: don't use getNamespace for getting function name

### PR DESCRIPTION
**Pull request by m-muecke**
There is probably a reason why it was done like that, but I would argue fetching the function name like is quite uncommon.

Changes:

* Use recommended `I("my_schema.my_table")` syntax for accessing schemas https://dbplyr.tidyverse.org/reference/in_schema.html
* Use `nzchar()` to check empty strings
* Replace `getNamespace(pkg)$fn` with `pkg::fn`

### CODE REVIEW

**Comment by christophscheuch** [comment]
We went for `getNamespace(pkg)$fn` to avoid having a lot of required packages because afaik `pkg::fn` need to be included as imports. The reasoning behind this decision was that users who want to use the package for a specific data source might not necessarily care about the others. Do you know a better way?

We originally decided against `I("my_schema.my_table")` because we wanted to support `dbplyr` versions below 2.5.0 but it seems we had to keep this version for other reasons anyway. So I approve this change and `nzchar` usage.

**Comment by m-muecke** [comment]
> We went for `getNamespace(pkg)$fn` to avoid having a lot of required packages because afaik `pkg::fn` need to be included as imports. The reasoning behind this decision was that users who want to use the package for a specific data source might not necessarily care about the others. Do you know a better way?
> 
> We originally decided against `I("my_schema.my_table")` because we wanted to support `dbplyr` versions below 2.5.0 but it seems we had to keep this version for other reasons anyway. So I approve this change and `nzchar` usage.

When using base R the most common pattern is checking at the beginning of the function if the package is installed and throw and error otherwise, here an example in the lintr repo: https://github.com/r-lib/lintr/blob/f0d9407306d9c6d2f049ac6f698d2806d44a989c/R/cyclocomp_linter.R#L27

and when using rlang the pattern is the same but used with `rlang::check_installed()` instead, here an example from the ggplot package: https://github.com/tidyverse/ggplot2/blob/7fb4c382f9ea332844d469663a8047355a88dd7a/R/fortify.R#L29

The key with both is that you don't import the package i.e. add it to the NAMESPACE file and call the function with `pkg::fn`

**Comment by christophscheuch** [comment]
Thanks, I also just discovered this in Hadley's book: https://r-pkgs.org/dependencies-in-practice.html#sec-dependencies-in-suggests-r-code. I'll run devtools::check() later today just to confirm and will merge the PR afterwards.

**Comment by m-muecke** [comment]
> Thanks, I also just discovered this in Hadley's book: https://r-pkgs.org/dependencies-in-practice.html#sec-dependencies-in-suggests-r-code. I'll run devtools::check() later today just to confirm and will merge the PR afterwards.

Always a good reference. Btw. let me know if you are even open for PRs since I've never explicitly asked.

**Comment by christophscheuch** [comment]
> > Thanks, I also just discovered this in Hadley's book: https://r-pkgs.org/dependencies-in-practice.html#sec-dependencies-in-suggests-r-code. I'll run devtools::check() later today just to confirm and will merge the PR afterwards.
> 
> Always a good reference. Btw. let me know if you're even open for PRs since I've never explicitly asked and these refactoring PRs can be quite annoying.

Please keep the suggestions coming, I'm always learning something new :)

**Pull request merged**
